/*
 * PUEDE INCLUIR DEFINICIONES COMPARTIDAS ENTRE EL WORKER Y LOS PROCESOS QUE
 * ACTUÁN DE CLIENTES DEL MISMO (MAP), SI LAS HUBIERA.
 */

#ifndef _WORKER_H
#define _WORKER_H        1

#endif // _WORKER_H

