/*
 * PUEDE INCLUIR DEFINICIONES COMPARTIDAS ENTRE EL MANAGER Y LOS PROCESOS QUE
 * ACTUÁN DE CLIENTES DEL MISMO (EL MAP Y LOS WORKERS),
 * SI LAS HUBIERA.
 */

#ifndef _MANAGER_H
#define _MANAGER_H        1

#endif // _MANAGER_H

