/*
 * PUEDE INCLUIR EN ESTE FICHERO LAS DEFICIONES QUE NECESITAN COMPARTIR
 * EL MANAGER, LOS WORKERS Y EL MAP, SI ES QUE LAS HUBIERA.
 */

#ifndef _COMMON_H
#define _COMMON_H        1

#endif // _COMMON_H
